### ISSUE TITLE
www.ttss.krakow.pl unavailable

### ISSUE THREAD

**Issue by galandilias** [PiotrMachowski/Home-Assistant-custom-components-MPK-KR#4]
Sypie mi od jakiegos czasu integracja ze sie nie moze polaczyc z ttss.krakow.pl - cos wiadomo co sie zmienilo? Dzialalo elegancko wszystko do niedawna - zakladam ze cos po stronie platformy komunikacyjnej Krakowa sie dzieje.

```
2024-05-27 19:30:20.364 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.mpk_kr_3040_tram_departure fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8b3eac1bb0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.ttss.krakow.pl', port=80): Max retries exceeded with url: /internetservice/services/passageInfo/stopPassages/stop?stop=3040&mode=departure&language=pl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b3eac1bb0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1295, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mpk_kr/sensor.py", line 111, in update
    data = MpkKrSensor.get_data(self._stop_id, self._platform, self._mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mpk_kr/sensor.py", line 197, in get_data
    response = requests.get(address)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.ttss.krakow.pl', port=80): Max retries exceeded with url: /internetservice/services/passageInfo/stopPassages/stop?stop=3040&mode=departure&language=pl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b3eac1bb0>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by PiotrMachowski** [comment]
Jaką masz konfigurację?

**Comment by galandilias** [comment]
```yaml
sensor:
  - platform: mpk_kr
    stops:
      - id: 3040
        platform: tram
        mode: departure
        directions:
          - "Kurdwanów P+R"
          - "Bronowice Małe"
          - "Czerwone Maki P+R"
          - "Nowy Bieżanów P+R"
```

Nic szczegolnego ;)

**Comment by PiotrMachowski** [comment]
Sprawdziłem i u mnie działa. Zobacz, czy jak wejdziesz pod poniższy adres, to u Ciebie jest ok:
http://www.ttss.krakow.pl/internetservice/services/passageInfo/stopPassages/stop?stop=3040&mode=departure&language=pl

**Comment by galandilias** [comment]
Dziala - czy to mozliwe ze blokuje ruch cos po ich stronie w przypadku wielokrotnego odpytywania?

**Comment by PiotrMachowski** [comment]
Możliwe. Restart HA coś zmienia?

**Comment by galandilias** [comment]
Tak - ale nie na dlugo... IP to samo zostaje - takze nie umiem sobie tego wyjasnic w kwestii blokowania po stronie MPK

**Comment by PiotrMachowski** [comment]
Ile działa po restarcie? Dodałem integrację u siebie, zobaczymy, czy mnie też zablokują

Możesz spróbować zwiększyć czas pomiędzy aktualizacjami:
```yaml
sensor:
  - platform: mpk_kr
    scan_interval: 60
    stops:
      - id: 3040
        platform: tram
        mode: departure
        directions:
          - "Kurdwanów P+R"
          - "Bronowice Małe"
          - "Czerwone Maki P+R"
          - "Nowy Bieżanów P+R"
```

**Comment by galandilias** [comment]
Teraz nie dziala - juz od paru dni - TTSS takze... :/

**Comment by PiotrMachowski** [comment]
Nie wiem, czy jestem w stanie coś poradzić na taką blokadę... Jedyne, co mi przychodzi do głowy, to bardzo mocno zwiększyć interwał aktualizacji i ręcznie aktualizować encję wywołując usługę `homeassistant.update_entity`

**Comment by galandilias** [comment]
Wlasnie nie wiem czy to blokada - bo nie dziala w ogole TTSS...

**Comment by galandilias** [comment]
tu jest github TTSS - tylko ja do konca nie wiem jak opisac problem ;)

https://github.com/jacekkow/mpk-ttss/issues

edit:
Patrze dalej i widze ze strona miasta w ogole nie odpowiada - to moze byc pierwotna przyczyna...

http://www.ttss.krakow.pl/internetservice/

**Comment by PiotrMachowski** [comment]
> Patrze dalej i widze ze strona miasta w ogole nie odpowiada - to moze byc pierwotna przyczyna...

Faktycznie, no to wszystko jasne

**Comment by galandilias** [comment]
![obraz](https://github.com/user-attachments/assets/fda8651c-f6a9-4f78-af0d-7dfb26850d17)

Odpowiedz z urzedu - tak sie robi aktualizacje systemow :P pol roku nie bedzie dzialac i to jest okej! :D

**Comment by PiotrMachowski** [comment]
🤦‍♂️

**Comment by PiotrWodecki** [comment]
Wygląda na to, że system powrócił. Po [zmianie urli na https](https://github.com/PiotrMachowski/Home-Assistant-custom-components-MPK-KR/pull/5) komponent działa
